### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by Dimitreee** [neodiX42/MyLocalTon#2]
Пытаюсь локально все развернуть и запустить, но столкнулся с ошибкой:

```
➜  MyLocalTon git:(main) ✗ java -jar MyLocalTon.jar


22:26:54.603 [main] INFO  org.ton.main.Main - myLocalTon lock file location: /Users/barrylarge/myLocalTon.lock
22:26:54.619 [MyLocalTon - main] INFO  org.ton.main.Main - Starting application at path /Users/barrylarge/Personal/MyLocalTon/MyLocalTon.jar
2022-02-02 22:26:55.674 java[25901:2725054] Persistent UI failed to open file file:///Users/barrylarge/Library/Saved%20Application%20State/net.java.openjdk.java.savedState/window_1.data: No such file or directory (2)
22:26:55.692 [MyLocalTon - main] INFO  org.ton.main.App - myLocalTon config file location: /Users/barrylarge/Personal/MyLocalTon/myLocalTon/settings.json
22:26:55.700 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Working Directory = /Users/barrylarge/Personal/MyLocalTon
22:26:55.700 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Binaries already extracted.
Feb 02, 2022 10:26:55 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4dca0ecd'
22:26:55.901 [MyLocalTon - main] INFO  org.ton.actions.MyLocalTon - Initializing genesis network
22:26:55.948 [JavaFX Application Thread] INFO  org.ton.main.App - Starting application
Exception in thread "MyLocalTon - main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.ton.actions.MyLocalTon.generateValidatorKeys(MyLocalTon.java:537)
	at org.ton.actions.MyLocalTon.initGenesis(MyLocalTon.java:172)
	at org.ton.main.App.main(App.java:99)
	at org.ton.main.Main.main(Main.java:37)
```

Сама нода и блокчейн не инициализируются.

- Платформа:  MacBook Pro (13-inch, M1, 2020)
- ОС: macOS BigSur 11.6.1 (20G224)
- Процессор: Apple M1
- openjdk version "17.0.2" 2022-01-18
- OpenJDK Runtime Environment (build 17.0.2+8-86)
- OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
- Сборка: https://github.com/neodiX42/MyLocalTon/actions/runs/1741478595

**Comment by neodiX42** [comment]
Apple M1 пока что неподдерживается. В течении месяца планирую добавить.

**Comment by Dimitreee** [comment]
Нужна помощь?

**Comment by neodiX42** [comment]
Пригодилась бы) Напиши мне в тг @neodix

**Comment by Dimitreee** [comment]
Solved, fix will be released soon.

**Comment by neodiX42** [comment]
The fix has been pushed to the main branch. Please check out for the latest release:
https://github.com/neodiX42/MyLocalTon/actions/runs/1790064172

Thanks @Dimitreee for the prompt support in enabling MacOS M1 support.
