### ISSUE TITLE
Version 103 forever initializing

### ISSUE THREAD

**Issue by qb60** [neodix42/MyLocalTon#24]
Hello. 
Version 103 is always showing initializing on start.

I see an error in debug log:
```
...
15:44:19.421 [MyLocalTon - main] DEBUG org.ton.actions.MyLocalTon - Initializing genesis network
15:44:19.423 [MyLocalTon - main] DEBUG o.t.e.g.RandomIdExecutor - execute: /home/user/ton/myLocalTon/genesis/bin/generate-random-id -m keys -n /home/user/ton/myLocalTon/genesis/db/keyring/validator
15:44:19.438 [MyLocalTon - main] DEBUG o.t.e.v.ValidatorEngine - genesis, validatorPrvKeyHex 9F1D907EAEC1671A467005FA68EEDE079223D132195F7FBC6C6CD0559140E6BB, validatorPrvKeyBase64 nx2Qfq7BZxpGcAX6aO7eB5Ij0TIZX3+8bGzQVZFA5rs=
15:44:19.477 [MyLocalTon - main] DEBUG o.t.e.c.CreateStateExecutor - execute: /home/user/ton/myLocalTon/genesis/bin/create-state /home/user/ton/myLocalTon/genesis/bin/smartcont/gen-zerostate.fif
15:44:19.518 [MyLocalTon - main] DEBUG o.t.e.v.ValidatorEngine - creating zero-state output: [ 1][t 0][2024-01-30 10:44:19.515903983][Fift.cpp:67]	top: include
level 1: <text interpreter continuation>
[ 1][t 0][2024-01-30 10:44:19.515920049][create-state.cpp:828]	Error interpreting application-specific preamble file `CreateState.fif`: CreateState.fif:241:	include:cannot locate file `auto/wallet-code.fif`
Check that correct include path is set by -I or by FIFTPATH environment variable, or disable standard preamble by -n.[0m

15:44:19.519 [MyLocalTon - main] DEBUG org.ton.main.Main - UI Uncaught Exception in thread 'MyLocalTon - main': Cannot invoke "String.split(String)" because "mainWalletAddrBoth" is null
15:44:19.520 [MyLocalTon - main] DEBUG org.ton.main.Main - java.lang.NullPointerException: Cannot invoke "String.split(String)" because "mainWalletAddrBoth" is null
	at org.ton.executors.validatorengine.ValidatorEngine.generateZeroState(ValidatorEngine.java:202)
	at org.ton.executors.validatorengine.ValidatorEngine.createZeroState(ValidatorEngine.java:150)
	at org.ton.actions.MyLocalTon.initGenesis(MyLocalTon.java:234)
	at org.ton.main.App.main(App.java:148)
	at org.ton.main.Main.main(Main.java:45)

15:44:20.986 [pool-6-thread-1] DEBUG org.ton.db.DbPool - new spawning prepared
```

**OS**: Ubuntu 22.04, x86-64.

Version 93 is working okay though.

I checked path `MyLocalTon.jar/org/ton/binaries/ton-linux-x86_64.zip/smartcont` and version 93 has folder `auto` there but version 103 - doesn't.

**Comment by neodix42** [comment]
Accepted. Missed that one. Should be a quick fix within 24h. Thanks for reporting.

**Comment by neodix42** [comment]
Please try v104

**Comment by qb60** [comment]
Now it's working, thank you.
