### ISSUE TITLE
Unable to start in container

### ISSUE THREAD

**Issue by qpb8023** [neodix42/MyLocalTon#29]
Hello, I cannot start MyLocalTon in the container. I use `MyLocalTon v110`, `openjdk:17-bullseye` as the container. When I execute the `java -jar MyLocalTon-x86-64.jar` command, the following error occurs:

```
09:12:07.046 [main] INFO  org.ton.main.Main - myLocalTon config file location: //myLocalTon/settings.json
09:12:07.049 [main] INFO  org.ton.main.Main - You are using headless version of Java. GUI will not be available.
09:12:07.051 [MyLocalTon - main] INFO  org.ton.main.Main - Starting application at path /MyLocalTon-x86-64.jar
09:12:07.057 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Working Directory = /
09:12:07.058 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Binaries already extracted.
09:12:07.154 [MyLocalTon - main] INFO  o.ton.executors.dhtserver.DhtServer - genesis dht-server started at 127.0.0.1:6302
09:12:07.155 [MyLocalTon - main] INFO  o.t.e.v.ValidatorEngine - starting validator-engine genesis
09:12:07.159 [MyLocalTon - main] INFO  o.t.e.v.ValidatorEngine - genesis validator-engine started at 127.0.0.1:4442
09:13:17.228 [MyLocalTon - main] INFO  org.ton.utils.MyLocalTonUtils - genesis is out of sync by 5 seconds
09:13:17.229 [MyLocalTon - main] INFO  org.ton.utils.MyLocalTonUtils - genesis synchronized
09:13:17.729 [MyLocalTon - main] INFO  org.ton.actions.MyLocalTon - Starting node monitor
Detected OS linux, amd64
Detected OS linux, amd64
09:13:17.738 [MyLocalTon - Dump Block 0] INFO  org.ton.actions.MyLocalTon - (-1,8000000000000000,157)
Java Tonlib configuration:
Location: tonlibjson.so
Verbosity level: FATAL (0)
Keystore in memory: false
Keystore path: //myLocalTon/genesis/bin/tonlib-keystore/
Path to global config: //myLocalTon/genesis/db/my-ton-global.config.json
Global config as string: 
Ignore cache: true
Testnet: false
Receive timeout: 10.0 seconds
Receive retry times: 3
[ 4][t 1][2024-07-22 09:13:17.917491874][TonlibClient.cpp:2218][!Tonlib][&tonlib_query] Tonlib got query [id:1] setLogVerbosityLevel {
  new_verbosity_level = 0
}
[ 4][t 1][2024-07-22 09:13:17.917541297][TonlibClient.cpp:2257][!Tonlib][&tonlib_query] Tonlib got static query setLogVerbosityLevel {
  new_verbosity_level = 0
}
set verbosityLevel result: {"@type":"ok"}
set tonlib configuration result {"@type":"options.info","config_info":{"@type":"options.configInfo","default_wallet_id":"1549654503","default_rwallet_init_public_key":"Puasxr0QfFZZnYISRphVse7XHKfW7pZU5SJarVHXvQ+rpzkD"}}
Detected OS linux, amd64
Java Tonlib configuration:
Location: tonlibjson.so
Verbosity level: FATAL (0)
Keystore in memory: false
Keystore path: //myLocalTon/genesis/bin/tonlib-keystore/
Path to global config: //myLocalTon/genesis/db/my-ton-global.config.json
Global config as string: 
Ignore cache: true
Testnet: false
Receive timeout: 10.0 seconds
Receive retry times: 3
[ 4][t 1][2024-07-22 09:13:18.065217404][TonlibClient.cpp:2218][!Tonlib][&tonlib_query] Tonlib got query [id:1] setLogVerbosityLevel {
  new_verbosity_level = 0
}
[ 4][t 0][2024-07-22 09:13:18.065255195][Client.cpp:78][&tonlib_requests]       Begin to wait for updates with timeout 10.000000
[ 4][t 1][2024-07-22 09:13:18.065288009][TonlibClient.cpp:2257][!Tonlib][&tonlib_query] Tonlib got static query setLogVerbosityLevel {
  new_verbosity_level = 0
}
set verbosityLevel result: {"@type":"ok"}
set tonlib configuration result {"@type":"options.info","config_info":{"@type":"options.configInfo","default_wallet_id":"1549654503","default_rwallet_init_public_key":"Puasxr0QfFZZnYISRphVse7XHKfW7pZU5SJarVHXvQ+rpzkD"}}
09:13:18.073 [MyLocalTon - main] INFO  org.ton.main.App - TON blockchain is ready!
09:13:18.090 [MyLocalTon - main] ERROR org.ton.db.DbPool - Error getNumberOfWalletsFromAllDBsAsync(), com.objectdb.o._PersistenceException: Failed to connect to server myLocalTon:6136 (myLocalTon)
09:13:19.091 [MyLocalTon - main] INFO  org.ton.actions.MyLocalTon - Creating initial wallets...
09:13:19.092 [MyLocalTon - main] ERROR org.ton.db.DbPool - Error existsMainWallet(), com.objectdb.o._PersistenceException: Failed to connect to server myLocalTon:6136 (myLocalTon)
09:13:19.111 [MyLocalTon - main] ERROR org.ton.actions.MyLocalTon - Error creating wallet! Error Failed to connect to server myLocalTon:6136 (myLocalTon) 
09:13:19.112 [MyLocalTon - main] ERROR org.ton.actions.MyLocalTon - [ObjectDB 2.8.6] javax.persistence.PersistenceException
Failed to connect to server myLocalTon:6136 (myLocalTon) (error 522)
        at com.objectdb.jpa.EMF.createEntityManager(EMF.java:152)
        at org.ton.db.DbPool.insertWallet(DbPool.java:234)
        at org.ton.executors.fift.Fift.getWalletByBasename(Fift.java:151)
        at org.ton.actions.MyLocalTon.createWalletEntity(MyLocalTon.java:442)
        at org.ton.actions.MyLocalTon.createWalletSynchronously(MyLocalTon.java:432)
        at org.ton.actions.MyLocalTon.createInitialWallets(MyLocalTon.java:399)
        at org.ton.main.App.main(App.java:176)
        at org.ton.main.Main.main(Main.java:91)
Caused by: com.objectdb.o.UserException: Failed to connect to server myLocalTon:6136 (myLocalTon)
        at com.objectdb.o.MSG.a(MSG.java:77)
        at com.objectdb.o.CLS.y(CLS.java:155)
        at com.objectdb.o.CST.<init>(CST.java:79)
        at com.objectdb.o.CSF.Z5(CSF.java:90)
        at com.objectdb.o.OMF.s(OMF.java:805)
        at com.objectdb.jpa.EMF.s(EMF.java:130)
        at com.objectdb.o.OMF.x(OMF.java:716)
        at com.objectdb.jpa.EMF.createEntityManager(EMF.java:149)
        ... 7 more
Caused by: java.net.UnknownHostException: myLocalTon
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at com.objectdb.o.CLS.y(CLS.java:123)
        ... 13 more

**Comment by undron** [comment]
Try `CMD [ "java", "-jar", "MyLocalTon-x86-64.jar", "nogui" ]`
