### ISSUE TITLE
Infinite initializing on v110 testnet

### ISSUE THREAD

**Issue by veebull** [neodix42/MyLocalTon#30]
Infinite initializing on v110 testnet
Macos Intel
java 17.0.1/22.0.1

logs
```02:43:27,216 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version ?
02:43:27,217 |-INFO in ch.qos.logback.classic.util.ContextInitializer@491666ad - No custom configurators were discovered as a service.
02:43:27,217 |-INFO in ch.qos.logback.classic.util.ContextInitializer@491666ad - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
02:43:27,218 |-INFO in ch.qos.logback.classic.util.ContextInitializer@491666ad - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
02:43:27,224 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
02:43:27,224 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
02:43:27,233 |-INFO in ch.qos.logback.classic.util.ContextInitializer@491666ad - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 6 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
02:43:27,233 |-INFO in ch.qos.logback.classic.util.ContextInitializer@491666ad - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
02:43:27,234 |-INFO in ch.qos.logback.classic.util.ContextInitializer@491666ad - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
02:43:27,234 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
02:43:27,238 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/justuser/Downloads/MyLocalTon-x86-64-testnet.jar!/logback.xml]
02:43:27,243 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@176d53b2 - URL [jar:file:/Users/justuser/Downloads/MyLocalTon-x86-64-testnet.jar!/logback.xml] is not of type file
02:43:27,344 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
02:43:27,344 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
02:43:27,351 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
02:43:27,381 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE-ROLLING]
02:43:27,381 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
02:43:27,392 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@158453976 - setting totalSizeCap to 10 GB
02:43:27,398 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@158453976 - Archive files will be limited to [10 MB] each.
02:43:27,400 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@158453976 - Will use gz compression
02:43:27,401 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@158453976 - Will use the pattern myLocalTon/archived/myLocalTon.%d{yyyy-MM-dd}.%i.log for the active file
02:43:27,425 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@51931956 - The date pattern is 'yyyy-MM-dd' from file name pattern 'myLocalTon/archived/myLocalTon.%d{yyyy-MM-dd}.%i.log.gz'.
02:43:27,425 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@51931956 - Roll-over at midnight.
02:43:27,434 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@51931956 - Setting initial period to 2024-07-29T21:43:27.434Z
02:43:27,436 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
02:43:27,440 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE-ROLLING] - Active log file name: myLocalTon/myLocalTon.log
02:43:27,440 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE-ROLLING] - File property is set to [myLocalTon/myLocalTon.log]
02:43:27,441 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE-ROLLING] - Failed to create parent directories for [/Library/Java/JavaVirtualMachines/myLocalTon/myLocalTon.log]
02:43:27,446 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE-ROLLING] - openFile(myLocalTon/myLocalTon.log,true) call failed. java.io.FileNotFoundException: myLocalTon/myLocalTon.log (No such file or directory)
	at java.io.FileNotFoundException: myLocalTon/myLocalTon.log (No such file or directory)
	at 	at java.base/java.io.FileOutputStream.open0(Native Method)
	at 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
	at 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:206)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:126)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:104)
	at 	at ch.qos.logback.core.model.processor.AppenderModelHandler.postHandle(AppenderModelHandler.java:84)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:208)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
	at 	at ch.qos.logback.classic.util.DefaultJoranConfigurator.configureByResource(DefaultJoranConfigurator.java:68)
	at 	at ch.qos.logback.classic.util.DefaultJoranConfigurator.configure(DefaultJoranConfigurator.java:35)
	at 	at ch.qos.logback.classic.util.ContextInitializer.invokeConfigure(ContextInitializer.java:128)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:103)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
	at 	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
	at 	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
	at 	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
	at 	at org.ton.main.Main.<clinit>(Main.java:20)
02:43:27,446 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
02:43:27,446 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
02:43:27,447 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE-ROLLING] to Logger[ROOT]
02:43:27,447 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@c8e4bb0 - End of configuration.
02:43:27,447 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6279cee3 - Registering current configuration as safe fallback point
02:43:27,447 |-INFO in ch.qos.logback.classic.util.ContextInitializer@491666ad - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 213 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY

02:43:27.517 [main] INFO  org.ton.main.Main - myLocalTon config file location: /Library/Java/JavaVirtualMachines/myLocalTon/settings.json
02:43:27.526 [MyLocalTon - main] INFO  org.ton.main.Main - Starting application at path /Users/justuser/Downloads/MyLocalTon-x86-64-testnet.jar
02:43:27.545 [pool-1-thread-1] ERROR org.ton.actions.MyLocalTon - Error saving settings.json file: Directory '/Library/Java/JavaVirtualMachines/myLocalTon' could not be created
02:43:27.546 [pool-1-thread-1] ERROR org.ton.actions.MyLocalTon - java.io.IOException: Directory '/Library/Java/JavaVirtualMachines/myLocalTon' could not be created
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2183)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3096)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3080)
	at org.ton.actions.MyLocalTon.saveSettingsToGsonSynchronized(MyLocalTon.java:284)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

02:43:28.681 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Working Directory = /Library/Java/JavaVirtualMachines
02:43:28.681 [MyLocalTon - main] INFO  org.ton.utils.Extractor - Detected OS: Mac OS X
июл. 30, 2024 2:43:28 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @56ed9f5e'```

**Comment by veebull** [comment]
solved
just add terminal to access change and delete applications in settings

**Comment by veebull** [comment]
solved
just add terminal to access change and delete applications in settings
